hello_azure/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('hello', views.hello, name='hello'),
    path('update', views.update, name='update'),
    path('home', views.home, name='home'),
    path('verify', views.verify, name='verify'),
    path('up', views.up, name='up'),
    path('upload', views.upload, name='upload'),
    path('add', views.add, name='add'),
    path('modify', views.modify, name='modify'),
    path('delete', views.delete, name='delete')
]

quickstartproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('hello_azure.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hello_azure/models.py
from django.db import models

# Create your models here.

class Csv(models.Model):
    file_name = models.FileField(upload_to='hello_azure')
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f"File id: {self.id}"

hello_azure/forms.py
import csv
from socket import fromshare
from django import forms
from .models import Csv

class CsvModelForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name',)

hello_azure/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore


import csv
from .forms import CsvModelForm
from .models import Csv

import pyrebase
config= {
  "apiKey": "AIzaSyC4Wop3qYzyJJyR6nES3V3_4ouh8XIxcFU",
  "authDomain": "discoapp-e8634.firebaseapp.com",
  "databaseURL": "https://discoapp-e8634-default-rtdb.firebaseio.com",
  "projectId": "discoapp-e8634",
  "storageBucket": "discoapp-e8634.appspot.com",
  "messagingSenderId": "1044386622635",
  "appId": "1:1044386622635:web:b52bd41e52dc3147289bee",
}
firebase=pyrebase.initialize_app(config)
authe = firebase.auth()
database=firebase.database()

# Use the application default credentials
# Creamos la conexión a la base de datos si no existe
if not firebase_admin._apps:
    # Es necesario configurar cred con la ruta del archivo json
    cred = credentials.Certificate("C:\Apps\discoapp-e8634-firebase-adminsdk-i64d2-9fe03f1fb7.json")
    # Inicializamos app
    firebase_admin.initialize_app(cred)

# Base de datos
db = firestore.client()


def index(request):
    print('Request for index page received')
    return render(request, 'hello_azure/index.html')

def update(request): #Esto es lo que agregamos
    print('Request for update page received')
    return render(request, 'hello_azure/update.html')

def up(request): #Esto es lo que agregamos
    print('Request for upload page received')
    return render(request, 'hello_azure/up.html')

def verify(request):
    day = database.get().val()
    return render(request, 'hello_azure/verify.html', {"prod":list(day.items())})

def home(request):
    print('Request for home page received')
    return render(request, 'hello_azure/hello.html')

#@csrf_exempt
# Para cargar los datos en la base de datos
def upload(request):
    form = CsvModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvModelForm()
        obj = Csv.objects.get(activated = False)
        doc_ref = db.collection(u'products')

        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)

            for i, row in enumerate(reader):
                if i == 0:
                    pass
                else:
                    row = "".join(row)
                    row = row.replace(";", " ")
                    row = row.split()
                    print(row)
                    if not row:
                        pass
                    else:
                        try:
                            int(row[1])
                        except ValueError:
                            print("Price is no numeric")
                            obj.delete()
                            return render(request, 'hello_azure/opss.html')
                        except IndexError:
                            print("Product or Price does not exist")
                            obj.delete()
                            return render(request, 'hello_azure/opss.html')
                        else:
                            doc_ref.document(row[0]+row[1]).set({
                                u'name': row[0],
                                u'price': int(row[1]),
                            })

            obj.activated = True
            obj.save()
            obj.delete()

        return render(request, 'hello_azure/succesful.html', {'form': form})
    return render(request, 'hello_azure/up.html', {'form': form})

@csrf_exempt
def hello(request):
    if request.method == 'POST':
        name = request.POST.get('username')
        pw = request.POST.get('password')
        
        if name is None or name == '':
            print("Request for hello page received with no name or blank name -- redirecting")
            return redirect('index')
        else:
            print("Request for hello page received with name=%s" % name)
            context = {'username': name }

            emails = []
            psswrds = []
            users_ref = db.collection(u'Users')
            docs = users_ref.stream()

            # Consultamos los ususarios y contraseñas en la base de datos
            for doc in docs:
                dictionary = doc.to_dict()
                #print(f'{doc.id} => {doc.to_dict()}')
                emails.append(dictionary.get("email"))
                psswrds.append(dictionary.get("password"))
            #print(emails,psswrds) 

            # Verificamos si el ussuario y contraseña coinciden con alguno en la base de datos
            for i in range (0,len(emails)):
                print(emails[i],psswrds[i])
                print(name, pw)
                if name == emails[i] and pw == psswrds[i]:
                    return render(request, 'hello_azure/hello.html', context)
            return redirect('index')
    else:
        return redirect('index')

@csrf_exempt
def add(request):
    if request.method == 'POST':
        product_name = request.POST.get('product_name1')
        product_price = request.POST.get('product_price1')
        
        if product_name is None or product_name == '' or product_price is None or product_price == '':
            print("Request to add received with no name or blank name -- redirecting")
            return redirect('update')
        else:
            print("Request to add received with name=%s" % product_name)
            doc_ref = db.collection(u'products')
            doc_ref.document(product_name+str(product_price)).set({
                                u'name': product_name,
                                u'price': product_price,
                            })
            return render(request, 'hello_azure/succesful.html')

@csrf_exempt
def modify(request):
    if request.method == 'POST':
        product_name = request.POST.get('product_name2')
        product_price = request.POST.get('product_price2')
        
        if product_name is None or product_name == '' or product_price is None or product_price == '':
            print("Request to modify received with no name or blank name -- redirecting")
            return redirect('update')
        else:
            print("Request to modify received with name=%s" % product_name)
            doc_ref = db.collection(u'products')
            docs = doc_ref.stream()

            for doc in docs:
                dictionary = doc.to_dict()
                p_name = dictionary.get("name")
                if p_name == product_name:
                    doc_ref.document(doc.id).set({
                                        u'name': product_name,
                                        u'price': product_price,
                                    })
            return render(request, 'hello_azure/succesful.html')

@csrf_exempt
def delete(request):
    if request.method == 'POST':
        product_name = request.POST.get('product_name3')
        
        if product_name is None or product_name == '':
            print("Request to delete received with no name or blank name -- redirecting")
            return redirect('update')
        else:
            print("Request to delete received with name=%s" % product_name)
            doc_ref = db.collection(u'products')
            docs = doc_ref.stream()

            for doc in docs:
                dictionary = doc.to_dict()
                p_name = dictionary.get("name")
                if p_name == product_name:
                    doc_ref.document(doc.id).delete()
                    return render(request, 'hello_azure/succesful.html')
            return render(request, 'hello_azure/notfound.html')

hello_azure/templates/hello_azure/hello.html
{% load static %}
<!doctype html>
<head>
  <img src="static/images/banner.png" width="1520" height="250">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'Logo_DiscoApp_ft.png' %}">
    
</head>

<html>
   <body class = 'bg-dark text-white' style="font-family: cursive;">
     <main>
        <div class="px-4 py-5 my-2 text-center">
            <h1 class="display-6 fw-bold">En esta página podrás subir, verificar y actualizar datos. </h1>
            <p class="fs-5">
              A continuación, encontraras una explicación de cada uno.
            </p>
        <!-- Descripciones y botones -->
        <div style='height: 550px; width: 320px; border: 0px; float: left; margin: 3em 0em 3em 10em; text-align: justify;'>
          <p class="fs-5">
            En esa sección encontraras la plantilla de Excel que te ayudara a organizar los datos que vayas a añadir a nuestra base de datos. Solo tienes que hacer clic aquí y seguir los pasos que aparecerán en pantalla.
          </p><br>
          <div style="text-align: center;"><a href="{% url 'up' %}" class="btn btn-outline-new btn-lg px-4 gap-1">Subir Datos</a></div>
        </div>

        <div style='height: 550px; width: 320px; border: 0px; float: left; text-align: justify;margin: 3em 0em 3em 7em'>
          <p class="fs-5">
            Aquí puedes consultar los datos que ya has introducido para verificar que estén correctos. Productos, precios y artículos aparecerán al presionar este botón.
          </p><br>
          <div style="text-align: center;"><a href="{% url 'verify' %}" class="btn btn-outline-new btn-lg px-4 gap-2">Verificar Datos</a></div>
        </div>

        <div style='height: 550px; width: 320px; border: 0px; float: left;margin: 3em 0em 3em 7em; text-align: justify;'>
          <p class="fs-5">
            Si encuentras algún error con un producto o alguno de sus parámetros cambio, en esta sección puedes actualizar esos datos para que no haya errores a futuro. 
         </p><br>
         <div style="text-align: center;"><a href="{% url 'update' %}" class="btn btn-outline-new btn-lg px-4 gap-3">Actualizar Datos</a></div>
        </div>
        </div>
     </main>      
   </body>
</html>

hello_azure/templates/hello_azure/index.html
{% load static %}
<!doctype html>
<head>
    <title>Bienvenido a DiscoApp</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'images/Logo_DiscoApp.png' %}">
</head>

<html>
   <body class="px-0 py-4 my-4 bg-dark text-center text-white">

     <style>


     h1 {
       font-family: 'Lucida Handwriting',sans-serif;
       text-align: center;
      }


     </style>

     <main>
       <!-- Parte del logo -->
          <div style='height: 550px; width: 485px; border: 0px; float: left; margin: 1em 0em 10em 10em; text-align: left;'>
            <div class="px-0 py-5 my-2 text-center">
              <img class="d-block mx-auto mb-4" src="static/images/Logo_DiscoApp.png"width="500" height="500"/>
            </div>
          </div>
        <!-- Parte de logos redes sociales -->
        <div style='height: 150px; width: 100px; border: 0px; float: left; margin: 7em 0em 10em 1em; text-align: left;'>
          <div class="px-0 py-5 my-2 text-center">
            <a href="https://instagram.com/discoapp2022?igshid=YmMyMTA2M2Y="><img class="d-block mx-auto mb-4" src="static/images/Logo_ig.png"width="70" height="70"/></a>
            <br>
            <a href="https://www.facebook.com/"><img class="d-block mx-auto mb-4" src="static/images/Logo_fb.png"width="70" height="70"/></a>
            <br>
            <a href="https://www.twitter.com/"><img class="d-block mx-auto mb-4" src="static/images/Logo_tw.png"width="70" height="70"/></a>
          </div>
        </div>
        <!-- Parte del login -->
        <form method="post" action="hello">
            {% csrf_token %}
        <!--
          <div style='height: 350px; width: 350px; border: 0px; float: left; margin: 10em 0em 3em 12em; text-align: center;'>
            <div class="px-0 py-10 my-2 text-center">
              <h1 class="display-6 fw-bold text-white">¡Bienvenido a DiscoApp!</h1> <br>
              <label for="name" class="form-label fw-bold fs-5">Iniciar sesión</label> <br>

              <div class="d-grid gap-2 d-sm-flex justify-content-sm-left align-items-center my-1">
                Correo electrónico:
                <input type="text" class="form-control" id="name" name="name" style="max-width: 287px;">
              </div>
              <div class="d-grid gap-2 d-sm-flex justify-content-sm-left align-items-center my-1">
                Contraseña:
                <input type="text" class="form-control" id="name" name="name" style="max-width: 256px;">
              </div>
              <br>
              <div class="d-grid gap-2 d-sm-flex justify-content-sm-center my-2">
                <button type="submit" class="btn btn-outline-new btn-lg px-4 gap-3">Ingresar</button>
              </div>
            </div>
          </div>-->
        <div style='height: 350px; width: 350px; border: 0px; float: left; margin: 5em 0em 3em 12em; text-align: center; font-family: cursive; font-size: 17px;'>
          <div class="px-0 py-10 my-2 text-center">
            <h1 class="display-7 fw-bold text-white">Bienvenido a DiscoApp</h1> <br>
            <div class="w3-container w3-teal">
              <div class="row">
                <div class="col-md-9 mx-auto">
                  <div class="card card-body bg-dark">
                    <form id="submitForm" action="#" method="post" data-parsley-validate="" data-parsley-errors-messages-disabled="true" novalidate="" _lpchecked="1">
                    <input type="hidden" name="_csrf" value="7635eb83-1f95-4b32-8788-abec2724a9a4">
                    <div class="form-group required text-white">
                      <lSabel for="username"> Correo electrónico</lSabel>
                      <input type="text" class="form-control text-lowercase" id="username" required="" name="username" value="">
                    </div><br>
                    <div class="form-group required">
                      <label class="d-flex flex-row align-items-center text-white" for="password"> Contraseña
                      <small>
                      <a class="ml-auto border-link small-xl" href="#"> ¿Olvidaste tu contraseña? </a> </label> </small>
                      <input type="password" class="form-control" required="" id="password" name="password" value="">
                    </div>
                    <div class="form-group mt-4 mb-4">
                      <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="remember-me" name="remember-me" data-parsley-multiple="remember-me">
                        <label class="custom-control-label text-white small" for="remember-me"> Recuérdame </label>
                      </div>
                    </div>
                    <div class="form-group pt-1">
                      <button type="submit" class="btn btn-outline-light btn-lg px-4 gap-3">Ingresar</button>
                    </div>
                    <p class="small-xl pt-4 text-center">
                      <a class="text-muted" href="#">
                        <small>
                        <span class="text-muted"> Regístrate </span>
                        </small>
                      </a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        </form>
     </main>
  </body>
</html>

hello_azure/templates/hello_azure/notfound.html
{% load static %}
<!doctype html>
<head>
  <img src="static/images/banner.png" width="1520" height="250">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'Logo_DiscoApp_ft.png' %}">
    
</head>

<html>
   <body class = 'bg-dark text-white'>
     <main>
        <div style = 'margin: 7em 10em 20em 10em; text-align: center;'>
            <h1>Producto no encontrado </h1><br><br><br>
            <a href="{% url 'update' %}" class="btn btn-outline-new btn-lg px-4 gap-2">Volver</a>
        </div>
     </main>      
   </body>
</html>

hello_azure/templates/hello_azure/opss.html
{% load static %}
<!doctype html>
<head>
  <img src="static/images/banner.png" width="1520" height="250">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'Logo_DiscoApp_ft.png' %}">
    
</head>

<html>
    <style>


        h1 {
          text-align: center;
          font-size: 40px;
          font-family: cursive;
          color: #fdfdfe;
         }

         h2 {
          text-align: justify;
          font-size: 25px;
          font-family: cursive;
          color: #fdfdfe;
         }

         h3 {
          text-align: justify;
          font-size: 20px;
          font-family: Verdana, Geneva, Tahoma, sans-serif;
          color: #fdfdfe;
         }
   
   
    </style>

   <body class = 'bg-dark'>
     <main>

        <div style='height: 550px; width: 400px; border: 0px; float: left; margin: 1em 2em 20em 10em; text-align: center;'>
            <img src="static/images/opss.png" width="310" height="250"><br><br><br>
            <h1>¡Oppss! Lo sentimos, Al parecer tuvimos un error al momento de cargar los datos. </h1><br>
        </div>

        <div style='height: 550px; width: 620px; border: 0px; float: left; margin: 2em 5em 20em 10em;text-align: center;'>
            <h2>Esto puede deberse a multiples razones. Te recomendamos verificar en tu archivo .csv lo siguiente:</h2><br>
            <h3>
                <li>Las columnas del archivo se encuentran en el orden de la plantilla (producto, precio).</li>
                <li>Todas las casillas tienen producto y precio.</li>
                <li>El precio está indicado en números.</li>
            </h3><br>
            <h2>¡Si tu archivo ya tiene estas características intenta subirlo nuevamente!.</h2><br>
            <h2>Si el error presiste, contáctate con nosotros para solucionarlo</h2><br>
            <a href="{% url 'up' %}" class="btn btn-outline-new btn-lg px-4 gap-2">Regresar</a>
        </div>

     </main>      
   </body>
</html>

hello_azure/templates/hello_azure/succesful.html
{% load static %}
<!doctype html>
<head>
  <img src="static/images/banner.png" width="1520" height="250">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'Logo_DiscoApp_ft.png' %}">
    
</head>

<html>
    <style>


        h1 {
          text-align: center;
          font-size: 70px;
          font-weight: 700;
          font-family: cursive;
          color: #fdfdfe;
          text-shadow: 0px 0px 5px #b393d3, 0px 0px 10px #b393d3, 0px 0px 10px #b393d3;
         }
   
   
    </style>

   <body class = 'bg-dark'>
     <main>
        <div style = 'margin: 7em 10em 20em 10em; text-align: center;'>
            <h1>Proceso exitoso :) </h1><br><br><br>
            <a href="{% url 'home' %}" class="btn btn-outline-new btn-lg px-4 gap-2">Volver a inicio</a>
        </div>
     </main>      
   </body>
</html>

hello_azure/templates/hello_azure/up.html
{% load static %}
<!doctype html>
<head>
  <img src="static/images/banner.png" width="1520" height="250">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'Logo_DiscoApp_ft.png' %}">
    
</head>

<html>
  <body class = 'bg-dark text-white'>
    <a href="{% url 'home' %}" class="btn btn-outline-new btn-lg px-4 gap-2">Volver a inicio</a>      
     <main>
        <div class="px-4 py-3 my-2 text-center">
            <h1 class="display-6 fw-bold">Subir datos.</h1>
            <p class="fs-5">
              En esta página puedes subir grandes volúmenes de datos en tres sencillos pasos &#128516;. Sigue las instrucciones:
            </p>
          <!-- Instrucciones -->
          <!-- Paso 1 -->
          <div style='height: 230px; width: 320px; border: 0px; float: left; margin: 5em 0em 3em 10em; text-align: left;'>
            <p class="fs-5">
              1. Descarga la plantilla haciendo click a continuación: 
            </p>
            <a href="static/Plantilla.csv" class="btn btn-outline-light btn-lg px-5 gap-3" download="plantilla.csv">Descargar plantilla excel</a>
          </div>
          <!-- Paso 2 -->
          <div style='height: 230px; width: 320px; border: 0px; float: left; text-align: left ;margin: 5em 0em 3em 7em'>
            <p class="fs-5">
              2. Abre la plantilla e ingresa los datos que te solicita.
              <ul style="font-size:15px">
                <li>Producto: Nombre del producto.</li>
                <li>Precio: Valor del producto asociado.</li>
              </ul>
            </p><p class="fs-5">Luego, guarda la plantilla con el nombre que quieras en formato .csv</p>
          </div>
          <!-- Paso 3 -->
          <div style='height: 230px; width: 320px; border: 0px; float: left;margin: 5em 0em 3em 7em; text-align: left;'>
            <p class="fs-5">
              3. Selecciona la plantilla haciendo click aquí &#128071;</p>
            <p class="fs-5">
              <form enctype="multipart/form-data"  method="post" action="upload">
                  {% csrf_token %}
                  <!--<input type="file" class="form-control" accept=".csv" name = "filename" style="max-width: 287px;">-->
                  <input type="hidden" name="csrfmiddlewaretoken" value="STQGqHQaVieDhYdEeaiJ5zVegfobsomY3jMMkqNdKfpD8Vuw3RdAogJAIx1ki480">
                  <tr>
                  <td>
                    <input type="file" name="file_name" required id="id_file_name" class="form-control" accept=".csv">
                  </td>
                </tr>
                  <button type="submit" class="btn btn-outline-light btn-sm px-4 gap-3">Subir archivos</button>
              </form>
              <!--<p class="fs-5">-->
                &#128070; Finalmente, haz click en subir archivos
              <!--</p>-->
            </p>
          </div>
        </div>
      </main>      
  </body>
</html>

hello_azure/templates/hello_azure/update.html
{% load static %}
<!doctype html>
<head>
  <img src="static/images/banner.png" width="1520" height="250">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'Logo_DiscoApp_ft.png' %}">
    
</head>

<html>

  <style>


    h1 {
      text-align: center;
      font-size: 40px;
      font-family: cursive;
      color: #fdfdfe;
     }

     h2 {
      text-align: center;
      font-size: 25px;
      font-family: cursive;
      color: #a4a4f6;
     }

     h3 {
      text-align: center;
      font-size: 20px;
      font-family: cursive;
      color: #fdfdfe;
     }

     h4 {
      text-align: justify;
      font-size: 20px;
      font-family: cursive;
      color: #fdfdfe;
     }

     h5 {
      text-align: Left;
      font-size: 17px;
      font-family: cursive;
      color: #c9c9ee;
     }

  </style>

  <body class = 'bg-dark text-white'>
    <a href="{% url 'home' %}" class="btn btn-outline-new btn-lg px-4 gap-2">Volver a inicio</a>      
     <main>
        <div class="px-4 py-3 my-2 text-center">
            <h1>Actualizar datos. </h1><br>
            <h3>
              En esta página puedes actualizar los datos de tu aplicación de acuerdo con la acción que deseas realizar.
            </h3>
          <!-- Instrucciones -->
          <!-- Opción 1 -->
          <div style='height: 520px; width: 340px; border: 0px; float: left; margin: 5em 0em 0em 7em; text-align: left;'>
            <h2>
              Opción 1: 
            </h2>
            <h3>Agregar nuevos datos</h3><br>
            <h4>Ingresa a continuación el nombre y el precio del producto en los espacios correspondientes. Luego haz click en agregar.</h4><br>
            <h3>
              <form method="post" action="add">
                {% csrf_token %}
                <h5>Nombre del producto:</h5>
                <input type="text" class="form-control" id = "product_name1" name = "product_name1" required=""><br>
                <h5>Precio:</h5>
                <input type="number" class="form-control" id = "product_price1" name = "product_price1" required="" ><br>
                <button type="submit" class="btn btn-outline-light btn-lg px-4 gap-3">Agregar</button>
              </form>
            </h3>
          </div>
          <!-- Opción 2 -->
          <div style='height: 520px; width: 340px; border: 0px; float: left; text-align: left ;margin: 5em 7em 0em 7em'>
            <h2>
              Opción 2: 
            </h2>
            <h3>Modificar datos</h3><br>
            <h4>Escribe el nombre y el nuevo precio del producto que quieres modificar. Después, presiona el botón modificar.</h4><br>
            <h3>
              <form method="post" action="modify">
                {% csrf_token %}
                <h5>Nombre del producto:</h5>
                <input type="text" class="form-control" id = "product_name2" name = "product_name2" required=""><br>
                <h5>Precio:</h5>
                <input type="number" class="form-control" id = "product_price2" name = "product_price2" required=""><br>
                <button type="submit" class="btn btn-outline-light btn-lg px-4 gap-3">Modificar</button>
              </form>
            </h3>
          </div>
          <!-- Opción 3 -->
          <div style='height: 520px; width: 340px; border: 0px; float: left;margin: 5em 7em 0em 0em; text-align: left;'>
            <h2>
              Opción 3: 
            </h2>
            <h3>Eliminar datos</h3><br>
            <h4>Ingresa el nombre del producto que quieres borrar de la base de datos. Al final, haz click en el botón eliminar.</h4><br>
            <h3>
              <form method="post" action="delete">
                {% csrf_token %}
                <h5>Nombre del producto:</h5>
                <input type="text" class="form-control" id = "product_name3" name = "product_name3" required=""><br>
                <button type="submit" class="btn btn-outline-light btn-lg px-4 gap-3">Eliminar</button>
              </form>
            </h3>
          </div>
        </div>
      </main>      
  </body>
</html>

hello_azure/templates/hello_azure/verify.html
{% load static %}
<!doctype html>
<head>
  <img src="static/images/banner.png" width="1520" height="250">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon"href="{% static 'Logo_DiscoApp_ft.png' %}">
    
</head>

<html>
  <body class = 'bg-dark text-white'>
    <a href="{% url 'home' %}" class="btn btn-outline-new btn-lg px-4 gap-2">Volver a inicio</a>    
      <main>
        <div style="text-align:center;">
        <table style="margin: 0 auto;">
          <tr>
            <th>Nombre</th>
            <th>Precio</th>
          </tr>
          {%for p in prod%}
          <tr>
            <td>{{p.0}}
            </td>
            <td>{{p.1}}</td>
          </tr>
          {%endfor%}
        </table>
        </div>
      </main>  
  </body>
</html>